name: CMake

on: 
  pull_request:
    branches: [ $default-branch ]
  push:
    
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Cache submodules
      uses: actions/cache@v1
      id: submodules-cache
      with:
        path: external
        key: ${{ runner.os }}-submodiles
    
    - name: Install submodules
      if: steps.submodules-cache.outputs.cache-hit != 'true'
      run: git submodule update --init
    
    - name: Install Vulkan
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.148-bionic.list https://packages.lunarg.com/vulkan/1.2.148/lunarg-vulkan-1.2.148-bionic.list
        sudo apt update
        sudo apt install vulkan-sdk

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        sudo apt-get install xorg-dev libglu1-mesa-dev

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
